export enum StateChangeType {
  ITEM_CLICK = 'ITEM_CLICK',
  ITEM_MOUSE_ENTER = 'ITEM_MOUSE_ENTER',
  SET_HIGHLIGHTED_INDEX = 'SET_HIGHLIGHTED_INDEX',
  SET_OPEN = 'SET_OPEN',
  MENU_MOUSE_LEAVE = 'MENU_MOUSE_LEAVE',
  INPUT_CHANGE = 'INPUT_CHANGE',
  KEY_PRESS_DOWN = 'KEY_PRESS_DOWN',
  KEY_PRESS_UP = 'KEY_PRESS_UP',
  KEY_PRESS_ESC = 'KEY_PRESS_ESC',
  KEY_PRESS_BACKSPACE = 'KEY_PRESS_BACKSPACE',
}
