name: CI

on:
  push:
    tags:
      - 'release-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nyaayaya/package-version@v1
        with:
          path: './package.json'
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: frontend
          SLACK_MESSAGE: 'Version updated :rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK}}
        with:
          text: Опубликован пакет ${{ github.repository }}@${{ env.PACKAGE_VERSION }}
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": {
                  "title": "Changelog",
                  "value": "${{ github.event.repository.url }}/blob/master/CHANGELOG.md"
                },
              },
            ]

