name: CI

on:
  push:
    tags:
      - 'release-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
      - uses: nyaayaya/package-version@v1
        with:
          path: './package.json'
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: frontend
          SLACK_MESSAGE: 'Version updated :rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
