name: Slack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nyaayaya/package-version@v1
        with:
          path: './package.json'
      - uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK}}
        with:
          text: Опубликован пакет ${GITHUB_REPOSITORY}@${{ env.PACKAGE_VERSION }}
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
              },
              {
                "title": "Changelog",
                "value": "${{ github.event.repository.url }}/blob/master/CHANGELOG.md"
              },
            ]

