name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nyaayaya/package-version@v1
        with:
          path: './package.json'
      - uses: wearerequired/slack-messaging-action@v1.0.1
        with:
          bot_token: ${{ secrets.SLACK_WEBHOOK }}
          channel: frontend
          payload: >-
            {
              "text": "Updated"
            }
